



GET http://localhost:3001/game/createNewGame HTTP/1.1

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"3a7e708b5e6e9aa7cc5a84f22a64cf1916688ce9",
    "currentPlayer":"P1",
    "pitNumber":3
}

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"3a7e708b5e6e9aa7cc5a84f22a64cf1916688ce9",
    "currentPlayer":"P2",
    "pitNumber":4
}

###
GET http://localhost:3001/game/list HTTP/1.1

###