



GET http://localhost:3001/game/createNewGame HTTP/1.1

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"83439f3c2199370482da33994915bf314d4d3336",
    "currentPlayer":"P1",
    "pitNumber":6
}

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"83439f3c2199370482da33994915bf314d4d3336",
    "currentPlayer":"P2",
    "pitNumber":4
}

###
GET http://localhost:3001/game/list HTTP/1.1

###