



GET http://localhost:3001/game/createNewGame HTTP/1.1

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"741f203c9d9c953e54b295f92d239f6c5f8431a8",
    "currentPlayer":"P1",
    "pitNumber":2
}

###

POST http://localhost:3001/game/attack HTTP/1.1
content-type: application/json

{
    "gameID":"741f203c9d9c953e54b295f92d239f6c5f8431a8",
    "currentPlayer":"P2",
    "pitNumber":2
}
###

GET http://localhost:3001/game/new HTTP/1.1

###
GET http://localhost:3001/game/list HTTP/1.1

###